linters-settings:
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
          - github.com/FloatTech
          - github.com/wdvxdr1123
          - github.com/fumiama
          - github.com/tidwall
          - jaytaylor.com/html2text
          - github.com/glebarez
          - github.com/sirupsen
          - github.com/gorilla
          - github.com/guohuiyuan
          - github.com/MoYoez
          - github.com/disintegration
          - github.com/playwright-community
          - github.com/mmcdole
          - github.com/go-resty
          - github.com/patrickmn
          - github.com/golang
          - github.com/wcharczuk

  errcheck:
    ignore: fmt:.*
    ignoretests: true

  goimports:
    local-prefixes: github.com/FloatTech/ZeroBot-Plugin-Playground

  forbidigo:
    # Forbid the following identifiers
    forbid:
      - ^fmt\.Errorf$ # consider errors.Errorf in github.com/pkg/errors

linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  fast: false
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - errcheck
    - exportloopref
    - exhaustive
    #- funlen
    #- goconst
    - gocritic
    #- gocyclo
    - gofmt
    - goimports
    - goprintffuncname
    #- gosec
    - gosimple
    - govet
    - ineffassign
    #- misspell
    - nolintlint
    - rowserrcheck
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - prealloc
    - predeclared
    - asciicheck
    - revive
    - forbidigo
    - makezero

run:
  # default concurrency is a available CPU number.
  # concurrency: 4 # explicitly omit this value to fully utilize available resources.
  deadline: 5m
  issues-exit-code: 1
  tests: false
  skip-dirs:
    - order
  go: '1.20'

# output configuration options
output:
  format: "colored-line-number"
  print-issued-lines: true
  print-linter-name: true
  uniq-by-line: true

issues:
  # Fix found issues (if it's supported by the linter)
  fix: true
  exclude-use-default: false
  exclude:
    - "Error return value of .((os.)?std(out|err)..*|.*Close|.*Seek|.*Flush|os.Remove(All)?|.*print(f|ln)?|os.(Un)?Setenv). is not check"
